image: python:latest

stages:
  - validate
  - publish

build:
  stage: validate
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" # Build only when a new branch is pushed or an existing branch is updated
  script:
    - pip install build
    - python -m build

publish:
  stage: publish
  rules:
    - if: $CI_PIPELINE_SOURCE == "web" # Publish only when the pipeline is created from a web request (merge request)
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - pip install build twine
    - python -m build
    - TWINE_PASSWORD=${CI_JOB_TOKEN} TWINE_USERNAME=gitlab-ci-token twine check dist/*
    - TWINE_PASSWORD=${CI_JOB_TOKEN} TWINE_USERNAME=gitlab-ci-token twine upload --repository-url ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi dist/*
